title: Gibraltar Telemedicine
email: hello@gbtelepsych.com
baseurl: ""
url: "http://camroncade.github.io/gibraltartelepsychiatry"

phoneDisplay: "(512) - 270 - 2884"
phone: "5122702884"

# Build settings
collections:
    solutions:
        output: true
        permalink: /solutions/:path/
    technology:
        output: true
        permalink: /technology/:path/
    careers:
        output: true
        permalink: /careers/:path/
